# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jcon2023-nbdev-demo',
                'doc_host': 'https://kzgrzendek.github.io',
                'git_url': 'https://github.com/kzgrzendek/jcon2023-nbdev-demo',
                'lib_path': 'jcon2023_nbdev_demo'},
  'syms': {'jcon2023_nbdev_demo.core': {'jcon2023_nbdev_demo.core.foo': ('core.html#foo', 'jcon2023_nbdev_demo/core.py')}}}
